### ISSUE TITLE
Shared_ptr not initialized

### ISSUE THREAD

**Issue by robbmcleod** [QSTEM/QSTEM#24]
msarahan/QSTEM/C++ refactor:

Stem3.exe crashes on  runtime with message, “Assertion failed: px != 0, file E:\lib\boost_1_55_0\boost/smart_ptr/shared_ptr.hpp, line 653” 

Debugged finds const boost::shared_ptrQSTEM::IConfigReader \* is the offender.  CConfigReaderFactory constructor does not initialize a pointer.  This may cause memory leak issues?  Browsing the various classes that sub-type shared_ptr they do  not seem to do pointer initialization.  Unsure on how to proceed to fix.

**Comment by msarahan** [comment]
This is (unfortunately) expected behavior right now.  The C++ refactor is not complete, and particularly, the Potential classes are not yet implemented.  This bug is just a not terribly informative symptom of this incompleteness.  I will document how to run the tests - they are the only part that currently runs.
